# Generated by Django 4.0.5 on 2022-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
